import logging
from typing import Dict
from prints_charming import PrintsStyle




DEFAULT_CONFIG: Dict[str, bool] = {
        "color_text"          : True,
        "args_to_strings"     : True,
        "style_names"         : True,
        "style_words_by_index": True,
        "kwargs"              : True,
        "conceal"             : True,
        "internal_logging"    : False,
        "log_level"           : 'DEBUG',  # Default to DEBUG level
}



DEFAULT_COLOR_MAP: Dict[str, str] = {
        "default": "\033[0m",
        "dfff": "\033[38;5;147m",
        "black": "\033[38;5;0m",
        "red": "\033[38;5;1m",
        "vred": "\033[38;5;196m",
        "green": "\033[38;5;34m",
        "vgreen": "\033[38;5;46m",
        "lblue": "\033[38;5;117m",
        "blue": "\033[38;5;4m",
        "dblue": "\033[38;5;27m",
        "vblue": "\033[38;5;39m",
        "lmagenta": "\033[38;5;205m",
        "magenta": "\033[38;5;5m",
        "vmagenta": "\033[38;5;198m",
        "lav": "\033[38;5;183m",
        "lpurple": "\033[38;5;135m",
        "purple": "\033[38;5;129m",
        "dpurple": "\033[38;5;93m",
        "lplum": "\033[38;5;177m",
        "plum": "\033[38;5;128m",
        "vplum": "\033[38;5;201m",
        "lpink": "\033[38;5;218m",
        "pink": "\033[38;5;206m",
        "vpink": "\033[38;5;199m",
        "cyan": "\033[38;5;6m",
        "vcyan": "\033[38;5;51m",
        "orange": "\033[38;5;208m",
        "vorange": "\033[38;5;202m",
        "copper": "\033[38;5;166m",
        "yellow": "\033[38;5;3m",
        "vyellow": "\033[38;5;226m",
        "gold": "\033[38;5;220m",
        "brass": "\033[38;5;178m",
        "bronze": "\033[38;5;136m",
        "lbrown": "\033[38;5;138m",
        "brown": "\033[38;5;94m",
        "sand": "\033[38;5;215m",
        "silver": "\033[38;5;12m",
        "dsilver": "\033[38;5;10m",
        "gray": "\033[38;5;248m",
        "dgray": "\033[38;5;8m",
        "plat": "\033[38;5;252m",
        "white": "\033[38;5;15m",
        "vwhite": "\033[38;5;231m"
}

DEFAULT_EFFECT_MAP: Dict[str, str] = {
        "reverse"      : "\033[7m",
        "bold"         : "\033[1m",
        "dim"          : "\033[2m",
        "italic"       : "\033[3m",
        "underline"    : "\033[4m",
        "overline"     : "\033[53m",
        "strikethru"   : "\033[9m",
        "conceal"      : "\033[8m",
        "blink"        : "\033[5m",
}

DEFAULT_STYLES: Dict[str, PrintsStyle] = {
        "default"      : PrintsStyle(),
        "class_name": PrintsStyle(color="dfff"),
        "method_name": PrintsStyle(color="lpurple"),
        "top_level_label": PrintsStyle(bold=True, italic=True),
        "sub_level_label": PrintsStyle(color='lblue'),
        "numbers"      : PrintsStyle(color="yellow"),
        'main_bullets' : PrintsStyle(color="purple"),
        "sub_bullets"  : PrintsStyle(color="pink"),
        "sub_proj"     : PrintsStyle(color="cyan"),
        "sub_bullet_title": PrintsStyle(color="orange"),
        "sub_bullet_sentence": PrintsStyle(color="dblue"),
        "default_bg"   : PrintsStyle(bg_color="black"),
        "white"        : PrintsStyle(color="white"),
        "gray"         : PrintsStyle(color="gray"),
        "dgray"        : PrintsStyle(color="dgray"),
        "black"        : PrintsStyle(color="black"),
        "green"        : PrintsStyle(color="green", bold=True),
        "vgreen"       : PrintsStyle(color="vgreen", bold=True),
        "log_true"     : PrintsStyle(color='vgreen'),
        "bg_color_green": PrintsStyle(color="white", bg_color='green'),
        "red"          : PrintsStyle(color="red"),
        "vred"         : PrintsStyle(color="vred", bold=True),
        "blue"         : PrintsStyle(color="blue"),
        "dblue"        : PrintsStyle(color="dblue"),
        "lblue"          : PrintsStyle(color="lblue"),
        "vblue"         : PrintsStyle(color="vblue"),
        "yellow"       : PrintsStyle(color="yellow"),
        "vyellow"      : PrintsStyle(color="vyellow"),
        "brass"        : PrintsStyle(color="brass"),
        "bronze"       : PrintsStyle(color="bronze"),
        "lbrown"       : PrintsStyle(color="lbrown"),
        "vorange"      : PrintsStyle(color="vorange"),
        "lplum"        : PrintsStyle(color="lplum"),
        "plum"         : PrintsStyle(color="plum"),
        "vplum"        : PrintsStyle(color="vplum"),
        "lmagenta"     : PrintsStyle(color="lmagenta"),
        "magenta"      : PrintsStyle(color="magenta", bold=True),
        "vmagenta"     : PrintsStyle(color="vmagenta"),
        "lpink"        : PrintsStyle(color="lpink"),
        "pink"         : PrintsStyle(color="pink",),
        "vpink"        : PrintsStyle(color="vpink"),
        "purple"       : PrintsStyle(color="purple"),
        "dpurple"      : PrintsStyle(color="dpurple"),
        "gold"         : PrintsStyle(color="gold"),
        "cyan"         : PrintsStyle(color="cyan"),
        "vcyan"        : PrintsStyle(color="vcyan"),
        "orange"       : PrintsStyle(color="orange"),
        "orangewhite"  : PrintsStyle(color="green", bg_color='dgray', underline=True),
        "copper"       : PrintsStyle(color="copper"),
        "brown"        : PrintsStyle(color="brown"),
        "sand"         : PrintsStyle(color="sand"),
        "lav"          : PrintsStyle(color="lav"),
        "lpurple"      : PrintsStyle(color="lpurple"),
        "plat"         : PrintsStyle(color="plat"),
        "silver"       : PrintsStyle(color="dfff", bg_color="dsilver"),
        "dfff"        : PrintsStyle(color="dfff", bg_color="purple", reverse=True),
        "vwhite"       : PrintsStyle(color="vwhite"),
        "header"       : PrintsStyle(color="vcyan"),
        "header_main"  : PrintsStyle(color="vcyan", bold=True),
        "header_text"  : PrintsStyle(color="purple", bg_color="gray", bold=True, italic=True),
        "header_text2" : PrintsStyle(color="gray", bg_color="purple", bold=True),
        "task"         : PrintsStyle(color="blue", bold=True),
        "path"         : PrintsStyle(color="blue"),
        "filename"     : PrintsStyle(color="yellow"),
        "line_info"    : PrintsStyle(color="yellow", bold=True),
        "line_number"  : PrintsStyle(color="orange", bold=True),
        "function_name": PrintsStyle(color="yellow", italic=True),
        "error_message": PrintsStyle(color="vred", bold=True, dim=True),
        "code"         : PrintsStyle(color="yellow"),
        "dict_key": PrintsStyle(color="lblue"),
        "dict_value": PrintsStyle(color="white"),
        "true": PrintsStyle(color="vgreen"),
        "false": PrintsStyle(color="vred"),
        'none': PrintsStyle(color="lpurple"),
        "int": PrintsStyle(color="cyan"),
        "float": PrintsStyle(color="vcyan"),
        "other": PrintsStyle(color="lav"),
        "conceal": PrintsStyle(conceal=True),
}

DEFAULT_LOGGING_STYLES: Dict[str, PrintsStyle] = {
        "default": PrintsStyle(),
        "timestamp": PrintsStyle(color="white"),
        "class_name": PrintsStyle(color="dfff"),
        "method_name": PrintsStyle(color="lpurple"),
        "line_number": PrintsStyle(color="lav"),
        "debug": PrintsStyle(color="blue"),
        "info": PrintsStyle(color="green"),
        "warning": PrintsStyle(color="yellow"),
        "error": PrintsStyle(color="red"),
        "critical": PrintsStyle(color="vred"),
        "dict_key": PrintsStyle(color="lblue"),
        "dict_value": PrintsStyle(color="white"),
        "true": PrintsStyle(color="vgreen"),
        "false": PrintsStyle(color="vred"),
        'none': PrintsStyle(color="lpurple"),
        "int": PrintsStyle(color="cyan"),
        "float": PrintsStyle(color="vcyan"),
        "other": PrintsStyle(color="lav"),
}


DEFAULT_LEVEL_STYLES = {
    logging.DEBUG: 'debug',
    logging.INFO: 'info',
    logging.WARNING: 'warning',
    logging.ERROR: 'error',
    logging.CRITICAL: 'critical'
}

